// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn TCP_ALLOWED_PORTS() -> SW::u16Array
{
  [5760u16]
}

pub fn UDP_ALLOWED_PORTS() -> SW::u16Array
{
  [68u16]
}

pub fn two_bytes_to_u16(
  byte0: u8,
  byte1: u8) -> u16
{
  ((byte0) as u16) * 256u16 + ((byte1) as u16)
}

pub fn frame_is_wellformed_eth2(aframe: SW::RawEthernetMessage) -> bool
{
  valid_frame_ethertype(aframe) & valid_frame_dst_addr(aframe)
}

pub fn valid_frame_ethertype(aframe: SW::RawEthernetMessage) -> bool
{
  frame_has_ipv4(aframe) |
    (frame_has_arp(aframe) | frame_has_ipv6(aframe))
}

pub fn valid_frame_dst_addr(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    !((aframe[0] == 0u8) &
      ((aframe[1] == 0u8) &
        ((aframe[2] == 0u8) &
          ((aframe[3] == 0u8) &
            ((aframe[4] == 0u8) &
              (aframe[5] == 0u8))))))
}

pub fn frame_has_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[12] == 8u8) &
      (aframe[13] == 0u8)
}

pub fn frame_has_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[12] == 134u8) &
      (aframe[13] == 221u8)
}

pub fn frame_has_arp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[12] == 8u8) &
      (aframe[13] == 6u8)
}

pub fn arp_has_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[16] == 8u8) &
      (aframe[17] == 0u8)
}

pub fn arp_has_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[16] == 134u8) &
      (aframe[17] == 221u8)
}

pub fn valid_arp_ptype(aframe: SW::RawEthernetMessage) -> bool
{
  arp_has_ipv4(aframe) | arp_has_ipv6(aframe)
}

pub fn valid_arp_op(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[20] == 0u8) &
      ((aframe[21] == 1u8) |
        (aframe[21] == 2u8))
}

pub fn valid_arp_htype(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[14] == 0u8) &
      (aframe[15] == 1u8)
}

pub fn wellformed_arp_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp_op(aframe) &
    (valid_arp_htype(aframe) & valid_arp_ptype(aframe))
}

pub fn valid_ipv4_length(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[16], aframe[17]) <= 9000u16)
}

pub fn valid_ipv4_protocol(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 0u8) |
      ((aframe[23] == 1u8) |
        ((aframe[23] == 2u8) |
          ((aframe[23] == 6u8) |
            ((aframe[23] == 17u8) |
              ((aframe[23] == 43u8) |
                ((aframe[23] == 44u8) |
                  ((aframe[23] == 58u8) |
                    ((aframe[23] == 59u8) |
                      (aframe[23] == 60u8)))))))))
}

pub fn valid_ipv4_vers_ihl(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[14] == 69u8)
}

pub fn wellformed_ipv4_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_protocol(aframe) &
    (valid_ipv4_length(aframe) & valid_ipv4_vers_ihl(aframe))
}

pub fn valid_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) & frame_has_ipv6(aframe)
}

pub fn valid_arp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &
    (frame_has_arp(aframe) & wellformed_arp_frame(aframe))
}

pub fn valid_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &
    (frame_has_ipv4(aframe) & wellformed_ipv4_frame(aframe))
}

pub fn ipv4_length(aframe: SW::RawEthernetMessage) -> u16
{
  two_bytes_to_u16(aframe[16], aframe[17])
}

pub fn valid_output_arp_size(output: SW::SizedEthernetMessage_Impl) -> bool
{
  output.sz == 64u16
}

pub fn valid_output_ipv4_size(
  input: SW::RawEthernetMessage,
  output: SW::SizedEthernetMessage_Impl) -> bool
{
  (input.len() == 1600) &&
    (output.sz == two_bytes_to_u16(input[16], input[17]) + 14u16)
}

pub fn allow_outbound_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp(aframe) | valid_ipv4(aframe)
}

pub fn ipv4_is_tcp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 6u8)
}

pub fn ipv4_is_udp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 17u8)
}

pub fn tcp_is_valid_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == TCP_ALLOWED_PORTS()[0])
}

pub fn udp_is_valid_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == UDP_ALLOWED_PORTS()[0])
}

pub fn udp_is_mavlink_src_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[34], aframe[35]) == 14550u16)
}

pub fn udp_is_mavlink_dst_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == 14562u16)
}

pub fn udp_is_mavlink(aframe: SW::RawEthernetMessage) -> bool
{
  udp_is_mavlink_src_port(aframe) & udp_is_mavlink_dst_port(aframe)
}

pub fn frame_has_ipv4_tcp_on_allowed_port_quant(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (0..=TCP_ALLOWED_PORTS().len() - 1).any(|i| TCP_ALLOWED_PORTS()[i] == two_bytes_to_u16(aframe[36], aframe[37]))
}

pub fn udp_is_valid_direct_dst_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (0..=UDP_ALLOWED_PORTS().len() - 1).any(|i| UDP_ALLOWED_PORTS()[i] == two_bytes_to_u16(aframe[36], aframe[37]))
}

pub fn valid_arp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &
    (frame_has_arp(aframe) & wellformed_arp_frame(aframe))
}

pub fn valid_ipv4_tcp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &
    (frame_has_ipv4(aframe) &
      (wellformed_ipv4_frame(aframe) & ipv4_is_tcp(aframe)))
}

pub fn valid_ipv4_udp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &
    (frame_has_ipv4(aframe) &
      (wellformed_ipv4_frame(aframe) & ipv4_is_udp(aframe)))
}

pub fn valid_ipv4_tcp_port(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_tcp(aframe) & frame_has_ipv4_tcp_on_allowed_port_quant(aframe)
}

pub fn valid_ipv4_udp_port(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_udp(aframe) &
    (udp_is_valid_direct_dst_port(aframe) & !(udp_is_mavlink(aframe)))
}

pub fn valid_ipv4_udp_mavlink(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_udp(aframe) & udp_is_mavlink(aframe)
}

pub fn allow_outbound_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp(aframe) |
    (valid_ipv4_udp_mavlink(aframe) | valid_ipv4_udp_port(aframe))
}

pub fn input_eq_mav_output_headers(
  aframe: SW::RawEthernetMessage,
  headers: SW::EthIpUdpHeaders) -> bool
{
  (aframe.len() == 1600) &&
    (0..=headers.len() - 1).all(|i| headers[i] == aframe[i])
}

pub fn input_eq_mav_output_payload(
  aframe: SW::RawEthernetMessage,
  payload: SW::UdpPayload,
  headers: SW::EthIpUdpHeaders) -> bool
{
  (aframe.len() == 1600) &&
    ((payload.len() == 1558) &&
      (0..=payload.len() - 1).all(|i| aframe[i + headers.len()] == payload[i]))
}

pub fn input_eq_mav_output(
  aframe: SW::RawEthernetMessage,
  output: SW::UdpFrame_Impl) -> bool
{
  input_eq_mav_output_headers(aframe, output.headers) & input_eq_mav_output_payload(aframe, output.payload, output.headers)
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx0
  *
  * guarantee valid_message_port0
  *  Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Guar_EthernetFramesRx0(EthernetFramesRx0: SW::RawEthernetMessage) -> bool
{
  valid_arp(EthernetFramesRx0) |
    (valid_ipv4_udp_mavlink(EthernetFramesRx0) |
      (valid_ipv4_udp_port(EthernetFramesRx0) | !(allow_outbound_frame(EthernetFramesRx0))))
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx0
  *
  * guarantee valid_message_port0
  *  Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Guar_Guard_EthernetFramesRx0(EthernetFramesRx0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRx0.is_some(),
    I_Guar_EthernetFramesRx0(EthernetFramesRx0.unwrap())
  )
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx1
  *
  * guarantee valid_message_port1
  *  Only valid messages being sent to the RxFirewall Port 1
  */
pub fn I_Guar_EthernetFramesRx1(EthernetFramesRx1: SW::RawEthernetMessage) -> bool
{
  valid_arp(EthernetFramesRx1) |
    (valid_ipv4_udp_mavlink(EthernetFramesRx1) |
      (valid_ipv4_udp_port(EthernetFramesRx1) | !(allow_outbound_frame(EthernetFramesRx1))))
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx1
  *
  * guarantee valid_message_port1
  *  Only valid messages being sent to the RxFirewall Port 1
  */
pub fn I_Guar_Guard_EthernetFramesRx1(EthernetFramesRx1: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRx1.is_some(),
    I_Guar_EthernetFramesRx1(EthernetFramesRx1.unwrap())
  )
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx2
  *
  * guarantee valid_message_port2
  *  Only valid messages being sent to the RxFirewall Port 2
  */
pub fn I_Guar_EthernetFramesRx2(EthernetFramesRx2: SW::RawEthernetMessage) -> bool
{
  valid_arp(EthernetFramesRx2) |
    (valid_ipv4_udp_mavlink(EthernetFramesRx2) |
      (valid_ipv4_udp_port(EthernetFramesRx2) | !(allow_outbound_frame(EthernetFramesRx2))))
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx2
  *
  * guarantee valid_message_port2
  *  Only valid messages being sent to the RxFirewall Port 2
  */
pub fn I_Guar_Guard_EthernetFramesRx2(EthernetFramesRx2: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRx2.is_some(),
    I_Guar_EthernetFramesRx2(EthernetFramesRx2.unwrap())
  )
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx3
  *
  * guarantee valid_message_port3
  *  Only valid messages being sent to the RxFirewall Port 3
  */
pub fn I_Guar_EthernetFramesRx3(EthernetFramesRx3: SW::RawEthernetMessage) -> bool
{
  valid_arp(EthernetFramesRx3) |
    (valid_ipv4_udp_mavlink(EthernetFramesRx3) |
      (valid_ipv4_udp_port(EthernetFramesRx3) | !(allow_outbound_frame(EthernetFramesRx3))))
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx3
  *
  * guarantee valid_message_port3
  *  Only valid messages being sent to the RxFirewall Port 3
  */
pub fn I_Guar_Guard_EthernetFramesRx3(EthernetFramesRx3: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRx3.is_some(),
    I_Guar_EthernetFramesRx3(EthernetFramesRx3.unwrap())
  )
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx0
  *
  * assume valid_tx_message_port0
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 0
  */
pub fn I_Assm_EthernetFramesTx0(EthernetFramesTx0: SW::SizedEthernetMessage_Impl) -> bool
{
  valid_arp(EthernetFramesTx0.amessage) & valid_output_arp_size(EthernetFramesTx0) |
    valid_ipv4(EthernetFramesTx0.amessage) & valid_output_ipv4_size(EthernetFramesTx0.amessage, EthernetFramesTx0)
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx0
  *
  * assume valid_tx_message_port0
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 0
  */
pub fn I_Assm_Guard_EthernetFramesTx0(EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTx0.is_some(),
    I_Assm_EthernetFramesTx0(EthernetFramesTx0.unwrap())
  )
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx1
  *
  * assume valid_tx_message_port1
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 1
  */
pub fn I_Assm_EthernetFramesTx1(EthernetFramesTx1: SW::SizedEthernetMessage_Impl) -> bool
{
  valid_arp(EthernetFramesTx1.amessage) & valid_output_arp_size(EthernetFramesTx1) |
    valid_ipv4(EthernetFramesTx1.amessage) & valid_output_ipv4_size(EthernetFramesTx1.amessage, EthernetFramesTx1)
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx1
  *
  * assume valid_tx_message_port1
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 1
  */
pub fn I_Assm_Guard_EthernetFramesTx1(EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTx1.is_some(),
    I_Assm_EthernetFramesTx1(EthernetFramesTx1.unwrap())
  )
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx2
  *
  * assume valid_tx_message_port2
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 2
  */
pub fn I_Assm_EthernetFramesTx2(EthernetFramesTx2: SW::SizedEthernetMessage_Impl) -> bool
{
  valid_arp(EthernetFramesTx2.amessage) & valid_output_arp_size(EthernetFramesTx2) |
    valid_ipv4(EthernetFramesTx2.amessage) & valid_output_ipv4_size(EthernetFramesTx2.amessage, EthernetFramesTx2)
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx2
  *
  * assume valid_tx_message_port2
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 2
  */
pub fn I_Assm_Guard_EthernetFramesTx2(EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTx2.is_some(),
    I_Assm_EthernetFramesTx2(EthernetFramesTx2.unwrap())
  )
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx3
  *
  * assume valid_tx_message_port3
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 3
  */
pub fn I_Assm_EthernetFramesTx3(EthernetFramesTx3: SW::SizedEthernetMessage_Impl) -> bool
{
  valid_arp(EthernetFramesTx3.amessage) & valid_output_arp_size(EthernetFramesTx3) |
    valid_ipv4(EthernetFramesTx3.amessage) & valid_output_ipv4_size(EthernetFramesTx3.amessage, EthernetFramesTx3)
}

/** I-Assm: Integration constraint on LowLevelEthernetDriver's incoming event data port EthernetFramesTx3
  *
  * assume valid_tx_message_port3
  *   Only valid ARP and IPV4 size messages transmitted by TxFirewall Port 3
  */
pub fn I_Assm_Guard_EthernetFramesTx3(EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  implies!(
    EthernetFramesTx3.is_some(),
    I_Assm_EthernetFramesTx3(EthernetFramesTx3.unwrap())
  )
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_EthernetFramesRx0 outgoing event data port
  * @param api_EthernetFramesRx1 outgoing event data port
  * @param api_EthernetFramesRx2 outgoing event data port
  * @param api_EthernetFramesRx3 outgoing event data port
  */
pub fn initialize_IEP_Post(
  api_EthernetFramesRx0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx3: Option<SW::RawEthernetMessage>) -> bool
{
  // I-Guar-Guard: Integration constraints for LowLevelEthernetDriver's outgoing ports"
  I_Guar_Guard_EthernetFramesRx0(api_EthernetFramesRx0) &
  I_Guar_Guard_EthernetFramesRx1(api_EthernetFramesRx1) &
  I_Guar_Guard_EthernetFramesRx2(api_EthernetFramesRx2) &
  I_Guar_Guard_EthernetFramesRx3(api_EthernetFramesRx3)
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for LowLevelEthernetDriver
  *
  * @param api_EthernetFramesTx0 incoming event data port
  * @param api_EthernetFramesTx1 incoming event data port
  * @param api_EthernetFramesTx2 incoming event data port
  * @param api_EthernetFramesTx3 incoming event data port
  */
pub fn compute_CEP_Pre(
  api_EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>) -> bool
{
  // I-Assm-Guard: Integration constraints for LowLevelEthernetDriver's incoming ports
  let r0: bool = I_Assm_Guard_EthernetFramesTx0(api_EthernetFramesTx0);
  let r1: bool = I_Assm_Guard_EthernetFramesTx1(api_EthernetFramesTx1);
  let r2: bool = I_Assm_Guard_EthernetFramesTx2(api_EthernetFramesTx2);
  let r3: bool = I_Assm_Guard_EthernetFramesTx3(api_EthernetFramesTx3);

  return r0 && r1 && r2 && r3;
}

/** CEP-Post: Compute Entrypoint Post-Condition for LowLevelEthernetDriver
  *
  * @param api_EthernetFramesTx0 incoming event data port
  * @param api_EthernetFramesTx1 incoming event data port
  * @param api_EthernetFramesTx2 incoming event data port
  * @param api_EthernetFramesTx3 incoming event data port
  * @param api_EthernetFramesRx0 outgoing event data port
  * @param api_EthernetFramesRx1 outgoing event data port
  * @param api_EthernetFramesRx2 outgoing event data port
  * @param api_EthernetFramesRx3 outgoing event data port
  */
pub fn compute_CEP_Post(
  api_EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesRx0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx3: Option<SW::RawEthernetMessage>) -> bool
{
  // I-Guar-Guard: Integration constraints for LowLevelEthernetDriver's outgoing ports
  let r0: bool = I_Guar_Guard_EthernetFramesRx0(api_EthernetFramesRx0);
  let r1: bool = I_Guar_Guard_EthernetFramesRx1(api_EthernetFramesRx1);
  let r2: bool = I_Guar_Guard_EthernetFramesRx2(api_EthernetFramesRx2);
  let r3: bool = I_Guar_Guard_EthernetFramesRx3(api_EthernetFramesRx3);

  return r0 && r1 && r2 && r3;
}
