// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_19_mav0_drop_mav_cmd_flash_bootloader
  * @param api_In0 incoming event data port
  * @param api_Out0 outgoing event data port
  */
pub fn compute_spec_hlr_19_mav0_drop_mav_cmd_flash_bootloader_guarantee(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_Out0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_In0.is_some() & GumboLib::msg_is_mav_cmd_flash_bootloader(api_In0.unwrap().payload),
    api_Out0.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_21_mav0_no_input
  * @param api_In0 incoming event data port
  * @param api_Out0 outgoing event data port
  */
pub fn compute_spec_hlr_21_mav0_no_input_guarantee(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_Out0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    !(api_In0.is_some()),
    api_Out0.is_none())
}

/** Compute Entrypoint Contract
  *
  * guarantee hlr_22_mav0_allow
  * @param api_In0 incoming event data port
  * @param api_Out0 outgoing event data port
  */
pub fn compute_spec_hlr_22_mav0_allow_guarantee(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_Out0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    api_In0.is_some() & !(GumboLib::msg_is_blacklisted(api_In0.unwrap().payload)),
    api_Out0.is_some() & GumboLib::mav_input_eq_output(api_In0.unwrap(), api_Out0.unwrap()))
}

/** CEP-T-Guar: Top-level guarantee contracts for MavlinkFirewall's compute entrypoint
  *
  * @param api_In0 incoming event data port
  * @param api_Out0 outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_Out0: Option<SW::RawEthernetMessage>) -> bool
{
  let r0: bool = compute_spec_hlr_19_mav0_drop_mav_cmd_flash_bootloader_guarantee(api_In0, api_Out0);
  let r1: bool = compute_spec_hlr_21_mav0_no_input_guarantee(api_In0, api_Out0);
  let r2: bool = compute_spec_hlr_22_mav0_allow_guarantee(api_In0, api_Out0);

  return r0 && r1 && r2;
}

/** CEP-Post: Compute Entrypoint Post-Condition for MavlinkFirewall
  *
  * @param api_In0 incoming event data port
  * @param api_In1 incoming event data port
  * @param api_In2 incoming event data port
  * @param api_In3 incoming event data port
  * @param api_Out0 outgoing event data port
  * @param api_Out1 outgoing event data port
  * @param api_Out2 outgoing event data port
  * @param api_Out3 outgoing event data port
  */
pub fn compute_CEP_Post(
  api_In0: Option<SW::UdpFrame_Impl>,
  api_In1: Option<SW::UdpFrame_Impl>,
  api_In2: Option<SW::UdpFrame_Impl>,
  api_In3: Option<SW::UdpFrame_Impl>,
  api_Out0: Option<SW::RawEthernetMessage>,
  api_Out1: Option<SW::RawEthernetMessage>,
  api_Out2: Option<SW::RawEthernetMessage>,
  api_Out3: Option<SW::RawEthernetMessage>) -> bool
{
  // CEP-Guar: guarantee clauses of MavlinkFirewall's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_In0, api_Out0);

  return r0;
}
