# Do not edit this file as it will be overwritten if codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

SYSTEM_FILE := $(TOP_DIR)/microkit.system
SCHEDULE_FILE := $(TOP_DIR)/microkit.schedule.xml

IMAGES := seL4_arduPilot_arduPilot.elf seL4_arduPilot_arduPilot_MON.elf seL4_mavlinkFirewall_mavlinkFirewall.elf seL4_mavlinkFirewall_mavlinkFirewall_MON.elf seL4_rxFirewall_firewall.elf seL4_rxFirewall_firewall_MON.elf seL4_txFirewall_firewall.elf seL4_txFirewall_firewall_MON.elf seL4_lowLevelEthernetDriver_lowLevelEthernetDriver.elf seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_1.o $(TOP_DIR)/build/sb_queue_SW_UdpFrame_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o $(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_SW_RawEthernetMessage_1.o: $(TOP_DIR)/types/src/sb_queue_SW_RawEthernetMessage_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_SW_UdpFrame_1.o: $(TOP_DIR)/types/src/sb_queue_SW_UdpFrame_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_SW_SizedEthernetMessage_1.o: $(TOP_DIR)/types/src/sb_queue_SW_SizedEthernetMessage_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
seL4_arduPilot_arduPilot_MON.o: $(TOP_DIR)/components/seL4_arduPilot_arduPilot/src/seL4_arduPilot_arduPilot_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_arduPilot_arduPilot/include

# user code
seL4_arduPilot_arduPilot_user.o: $(TOP_DIR)/components/seL4_arduPilot_arduPilot/src/seL4_arduPilot_arduPilot_user.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)/ -I$(TOP_DIR)/components/seL4_arduPilot_arduPilot/include

seL4_arduPilot_arduPilot.o: $(TOP_DIR)/components/seL4_arduPilot_arduPilot/src/seL4_arduPilot_arduPilot.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_arduPilot_arduPilot/include

# monitor
seL4_mavlinkFirewall_mavlinkFirewall_MON.o: $(TOP_DIR)/components/seL4_mavlinkFirewall_mavlinkFirewall/src/seL4_mavlinkFirewall_mavlinkFirewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_mavlinkFirewall_mavlinkFirewall/include

# user code
seL4_mavlinkFirewall_mavlinkFirewall_rust:
	make -C ${CRATES_DIR}/seL4_mavlinkFirewall_mavlinkFirewall $(RUST_MAKE_TARGET)

seL4_mavlinkFirewall_mavlinkFirewall.o: $(TOP_DIR)/components/seL4_mavlinkFirewall_mavlinkFirewall/src/seL4_mavlinkFirewall_mavlinkFirewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_mavlinkFirewall_mavlinkFirewall/include

# monitor
seL4_rxFirewall_firewall_MON.o: $(TOP_DIR)/components/seL4_rxFirewall_firewall/src/seL4_rxFirewall_firewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_rxFirewall_firewall/include

# user code
seL4_rxFirewall_firewall_rust:
	make -C ${CRATES_DIR}/seL4_rxFirewall_firewall $(RUST_MAKE_TARGET)

seL4_rxFirewall_firewall.o: $(TOP_DIR)/components/seL4_rxFirewall_firewall/src/seL4_rxFirewall_firewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_rxFirewall_firewall/include

# monitor
seL4_txFirewall_firewall_MON.o: $(TOP_DIR)/components/seL4_txFirewall_firewall/src/seL4_txFirewall_firewall_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_txFirewall_firewall/include

# user code
seL4_txFirewall_firewall_rust:
	make -C ${CRATES_DIR}/seL4_txFirewall_firewall $(RUST_MAKE_TARGET)

seL4_txFirewall_firewall.o: $(TOP_DIR)/components/seL4_txFirewall_firewall/src/seL4_txFirewall_firewall.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_txFirewall_firewall/include

# monitor
seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_MON.o: $(TOP_DIR)/components/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver/src/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver/include

# user code
seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_rust:
	make -C ${CRATES_DIR}/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver $(RUST_MAKE_TARGET)

seL4_lowLevelEthernetDriver_lowLevelEthernetDriver.o: $(TOP_DIR)/components/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver/src/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

seL4_arduPilot_arduPilot_MON.elf: seL4_arduPilot_arduPilot_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_arduPilot_arduPilot.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_arduPilot_arduPilot_user.o seL4_arduPilot_arduPilot.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_mavlinkFirewall_mavlinkFirewall_MON.elf: seL4_mavlinkFirewall_mavlinkFirewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_mavlinkFirewall_mavlinkFirewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_mavlinkFirewall_mavlinkFirewall_rust seL4_mavlinkFirewall_mavlinkFirewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_mavlinkFirewall_mavlinkFirewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_mavlinkFirewall_mavlinkFirewall -o $@

seL4_rxFirewall_firewall_MON.elf: seL4_rxFirewall_firewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_rxFirewall_firewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_rxFirewall_firewall_rust seL4_rxFirewall_firewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_rxFirewall_firewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_rxFirewall_firewall -o $@

seL4_txFirewall_firewall_MON.elf: seL4_txFirewall_firewall_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_txFirewall_firewall.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_txFirewall_firewall_rust seL4_txFirewall_firewall.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_txFirewall_firewall/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_txFirewall_firewall -o $@

seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_MON.elf: seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

seL4_lowLevelEthernetDriver_lowLevelEthernetDriver.elf: $(UTIL_OBJS) $(TYPE_OBJS) seL4_lowLevelEthernetDriver_lowLevelEthernetDriver_rust seL4_lowLevelEthernetDriver_lowLevelEthernetDriver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lseL4_lowLevelEthernetDriver_lowLevelEthernetDriver -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(SYSTEM_FILE)
	xmllint --xinclude $(SYSTEM_FILE) -o $(SYSTEM_FILE).merged
	$(MICROKIT_TOOL) $(SYSTEM_FILE).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu: $(IMAGE_FILE)
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/seL4_mavlinkFirewall_mavlinkFirewall test
	make -C ${CRATES_DIR}/seL4_rxFirewall_firewall test
	make -C ${CRATES_DIR}/seL4_txFirewall_firewall test
	make -C ${CRATES_DIR}/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver test

clean:: 
	make -C ${CRATES_DIR}/seL4_mavlinkFirewall_mavlinkFirewall clean
	make -C ${CRATES_DIR}/seL4_rxFirewall_firewall clean
	make -C ${CRATES_DIR}/seL4_txFirewall_firewall clean
	make -C ${CRATES_DIR}/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver clean

verus: 
	make -C ${CRATES_DIR}/seL4_mavlinkFirewall_mavlinkFirewall verus
	make -C ${CRATES_DIR}/seL4_rxFirewall_firewall verus
	make -C ${CRATES_DIR}/seL4_txFirewall_firewall verus
	make -C ${CRATES_DIR}/seL4_lowLevelEthernetDriver_lowLevelEthernetDriver verus
