// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn TCP_ALLOWED_PORTS() -> SW::u16Array
{
  [5760u16]
}

pub fn UDP_ALLOWED_PORTS() -> SW::u16Array
{
  [68u16]
}

pub fn two_bytes_to_u16(
  byte0: u8,
  byte1: u8) -> u16
{
  ((byte0) as u16) * 256u16 + ((byte1) as u16)
}

pub fn frame_is_wellformed_eth2(aframe: SW::RawEthernetMessage) -> bool
{
  valid_frame_ethertype(aframe) && valid_frame_dst_addr(aframe)
}

pub fn valid_frame_ethertype(aframe: SW::RawEthernetMessage) -> bool
{
  frame_has_ipv4(aframe) |
    (frame_has_arp(aframe) | frame_has_ipv6(aframe))
}

pub fn valid_frame_dst_addr(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    !((aframe[0] == 0u8) &&
      ((aframe[1] == 0u8) &&
        ((aframe[2] == 0u8) &&
          ((aframe[3] == 0u8) &&
            ((aframe[4] == 0u8) &&
              (aframe[5] == 0u8))))))
}

pub fn frame_has_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[12] == 8u8) &&
      (aframe[13] == 0u8))
}

pub fn frame_has_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[12] == 134u8) &&
      (aframe[13] == 221u8))
}

pub fn frame_has_arp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[12] == 8u8) &&
      (aframe[13] == 6u8))
}

pub fn arp_has_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[16] == 8u8) &&
      (aframe[17] == 0u8))
}

pub fn arp_has_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[16] == 134u8) &&
      (aframe[17] == 221u8))
}

pub fn valid_arp_ptype(aframe: SW::RawEthernetMessage) -> bool
{
  arp_has_ipv4(aframe) | arp_has_ipv6(aframe)
}

pub fn valid_arp_op(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[20] == 0u8) &&
      (aframe[21] == 1u8) |
        (aframe[21] == 2u8))
}

pub fn valid_arp_htype(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    ((aframe[14] == 0u8) &&
      (aframe[15] == 1u8))
}

pub fn wellformed_arp_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp_op(aframe) &&
    (valid_arp_htype(aframe) && valid_arp_ptype(aframe))
}

pub fn valid_ipv4_length(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[16], aframe[17]) <= 9000u16)
}

pub fn valid_ipv4_protocol(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 0u8) |
      ((aframe[23] == 1u8) |
        ((aframe[23] == 2u8) |
          ((aframe[23] == 6u8) |
            ((aframe[23] == 17u8) |
              ((aframe[23] == 43u8) |
                ((aframe[23] == 44u8) |
                  ((aframe[23] == 58u8) |
                    ((aframe[23] == 59u8) |
                      (aframe[23] == 60u8)))))))))
}

pub fn valid_ipv4_vers_ihl(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[14] == 69u8)
}

pub fn wellformed_ipv4_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_protocol(aframe) &&
    (valid_ipv4_length(aframe) && valid_ipv4_vers_ihl(aframe))
}

pub fn valid_ipv6(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) && frame_has_ipv6(aframe)
}

pub fn valid_arp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &&
    (frame_has_arp(aframe) && wellformed_arp_frame(aframe))
}

pub fn valid_ipv4(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &&
    (frame_has_ipv4(aframe) && wellformed_ipv4_frame(aframe))
}

pub fn ipv4_length(aframe: SW::RawEthernetMessage) -> u16
{
  two_bytes_to_u16(aframe[16], aframe[17])
}

pub fn valid_output_arp_size(output: SW::SizedEthernetMessage_Impl) -> bool
{
  output.sz == 64u16
}

pub fn valid_output_ipv4_size(
  input: SW::RawEthernetMessage,
  output: SW::SizedEthernetMessage_Impl) -> bool
{
  (input.len() == 1600) &&
    (output.sz == two_bytes_to_u16(input[16], input[17]) + 14u16)
}

pub fn tx_allow_outbound_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp(aframe) | valid_ipv4(aframe)
}

pub fn ipv4_is_tcp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 6u8)
}

pub fn ipv4_is_udp(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (aframe[23] == 17u8)
}

pub fn tcp_is_valid_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == TCP_ALLOWED_PORTS()[0])
}

pub fn udp_is_valid_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == UDP_ALLOWED_PORTS()[0])
}

pub fn udp_is_mavlink_src_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[34], aframe[35]) == 14550u16)
}

pub fn udp_is_mavlink_dst_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (two_bytes_to_u16(aframe[36], aframe[37]) == 14562u16)
}

pub fn udp_is_mavlink(aframe: SW::RawEthernetMessage) -> bool
{
  udp_is_mavlink_src_port(aframe) && udp_is_mavlink_dst_port(aframe)
}

pub fn frame_has_ipv4_tcp_on_allowed_port_quant(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (0..=TCP_ALLOWED_PORTS().len() - 1).any(|i| TCP_ALLOWED_PORTS()[i] == two_bytes_to_u16(aframe[36], aframe[37]))
}

pub fn udp_is_valid_direct_dst_port(aframe: SW::RawEthernetMessage) -> bool
{
  (aframe.len() == 1600) &&
    (0..=UDP_ALLOWED_PORTS().len() - 1).any(|i| UDP_ALLOWED_PORTS()[i] == two_bytes_to_u16(aframe[36], aframe[37]))
}

pub fn valid_ipv4_tcp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &&
    (frame_has_ipv4(aframe) &&
      (wellformed_ipv4_frame(aframe) && ipv4_is_tcp(aframe)))
}

pub fn valid_ipv4_udp(aframe: SW::RawEthernetMessage) -> bool
{
  frame_is_wellformed_eth2(aframe) &&
    (frame_has_ipv4(aframe) &&
      (wellformed_ipv4_frame(aframe) && ipv4_is_udp(aframe)))
}

pub fn valid_ipv4_tcp_port(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_tcp(aframe) && frame_has_ipv4_tcp_on_allowed_port_quant(aframe)
}

pub fn valid_ipv4_udp_port(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_udp(aframe) &&
    (udp_is_valid_direct_dst_port(aframe) && !(udp_is_mavlink(aframe)))
}

pub fn valid_ipv4_udp_mavlink(aframe: SW::RawEthernetMessage) -> bool
{
  valid_ipv4_udp(aframe) && udp_is_mavlink(aframe)
}

pub fn rx_allow_outbound_frame(aframe: SW::RawEthernetMessage) -> bool
{
  valid_arp(aframe) |
    (valid_ipv4_udp_mavlink(aframe) | valid_ipv4_udp_port(aframe))
}

pub fn input_eq_mav_output_headers(
  aframe: SW::RawEthernetMessage,
  headers: SW::EthIpUdpHeaders) -> bool
{
  (aframe.len() == 1600) &&
    (0..=headers.len() - 1).all(|i| headers[i] == aframe[i])
}

pub fn input_eq_mav_output_payload(
  aframe: SW::RawEthernetMessage,
  payload: SW::UdpPayload,
  headers: SW::EthIpUdpHeaders) -> bool
{
  (aframe.len() == 1600) &&
    ((payload.len() == 1558) &&
      (0..=payload.len() - 1).all(|i| aframe[i + headers.len()] == payload[i]))
}

pub fn input_eq_mav_output(
  aframe: SW::RawEthernetMessage,
  output: SW::UdpFrame_Impl) -> bool
{
  input_eq_mav_output_headers(aframe, output.headers) && input_eq_mav_output_payload(aframe, output.payload, output.headers)
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx0
  *
  * guarantee valid_message_port0
  *  Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Guar_EthernetFramesRx0(EthernetFramesRx0: SW::RawEthernetMessage) -> bool
{
  valid_arp(EthernetFramesRx0)
}

/** I-Guar: Integration constraint on LowLevelEthernetDriver's outgoing event data port EthernetFramesRx0
  *
  * guarantee valid_message_port0
  *  Only valid messages being sent to the RxFirewall Port 0
  */
pub fn I_Guar_Guard_EthernetFramesRx0(EthernetFramesRx0: Option<SW::RawEthernetMessage>) -> bool
{
  implies!(
    EthernetFramesRx0.is_some(),
    I_Guar_EthernetFramesRx0(EthernetFramesRx0.unwrap())
  )
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_EthernetFramesRx0 outgoing event data port
  * @param api_EthernetFramesRx1 outgoing event data port
  * @param api_EthernetFramesRx2 outgoing event data port
  * @param api_EthernetFramesRx3 outgoing event data port
  */
pub fn initialize_IEP_Post(
  api_EthernetFramesRx0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx3: Option<SW::RawEthernetMessage>) -> bool
{
  // I-Guar-Guard: Integration constraints for LowLevelEthernetDriver's outgoing ports"
  I_Guar_Guard_EthernetFramesRx0(api_EthernetFramesRx0)
}

/** CEP-Post: Compute Entrypoint Post-Condition for LowLevelEthernetDriver
  *
  * @param api_EthernetFramesTx0 incoming event data port
  * @param api_EthernetFramesTx1 incoming event data port
  * @param api_EthernetFramesTx2 incoming event data port
  * @param api_EthernetFramesTx3 incoming event data port
  * @param api_EthernetFramesRx0 outgoing event data port
  * @param api_EthernetFramesRx1 outgoing event data port
  * @param api_EthernetFramesRx2 outgoing event data port
  * @param api_EthernetFramesRx3 outgoing event data port
  */
pub fn compute_CEP_Post(
  api_EthernetFramesTx0: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx1: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx2: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesTx3: Option<SW::SizedEthernetMessage_Impl>,
  api_EthernetFramesRx0: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx1: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx2: Option<SW::RawEthernetMessage>,
  api_EthernetFramesRx3: Option<SW::RawEthernetMessage>) -> bool
{
  // I-Guar-Guard: Integration constraints for LowLevelEthernetDriver's outgoing ports
  let r0: bool = I_Guar_Guard_EthernetFramesRx0(api_EthernetFramesRx0);

  return r0;
}
