// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct UdpFrame {
    pub headers: EthIpUdpHeaders,
    pub payload: UdpPayload
  }

  impl Default for UdpFrame {
    fn default() -> Self
    {
      Self { headers: [0; SW::SW_EthIpUdpHeaders_DIM_0], payload: [0; SW::SW_UdpPayload_DIM_0] }
    }
  }
}