name: Verification and Build

on:
  push:
    branches: ["feb-2026"]
    paths:
      - '**.rs'
      - '**/Cargo**'
  pull_request:
    types: ["opened", "reopened", "edited"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  verify:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      packages: read
      attestations: read

    outputs:
      status-code: ${{ steps.verus.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Copy Verus action
      uses: actions/checkout@v4
      with:
        repository: loonwerks/INSPECTA-Verus-CI-Action
        path: INSPECTA-Verus-CI-Action
    - name: Verus Analysis
      id : verus
      uses: ./INSPECTA-Verus-CI-Action
      with:
        sourcepath: software/hamr/microkit
        outputfile: verus-report.json
    - name: Get analysis timestamp
      run: echo "Analysis timestamp is ${{ steps.verus.outputs.timestamp }}"
    - name: Get analysis status
      run: echo "Analysis status is ${{ steps.verus.outputs.status }}"
    - name: Echo status to output
      run: echo "status=${{ steps.verus.outputs.status }}" >> "$GITHUB_OUTPUT"
    - name: Archive analysis report
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: verus-analysis-report
        path: verus-report.json
        retention-days: 30

  codebuild:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      attestations: read

    outputs:
      status-code: ${{ steps.codebuild.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        submodules: true
        
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Copy Codebuild action
      uses: actions/checkout@v4
      with:
        repository: loonwerks/INSPECTA-Codebuild-CI-Action
        path: INSPECTA-Codebuild-CI-Action
    - name: Code Build
      id : codebuild
      uses: ./INSPECTA-Codebuild-CI-Action
      with:
        sourcepath: software/hamr/microkit
    - name: Get codebuild timestamp
      run: echo "Codebuild timestamp is ${{ steps.codebuild.outputs.timestamp }}"
    - name: Get codebuild status
      run: echo "Codebuild status is ${{ steps.build.codebuild.outputs.status }}"
    - name: Echo status to output
      run: echo "status=${{ steps.codebuild.outputs.status }}" >> "$GITHUB_OUTPUT"
    - name: Archive built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: codebuild-built-artifacts
        path: software/hamr/microkit/
        retention-days: 30
    - name: Count Lines of Code (cloc)
      if: ${{ always() }}
      uses: djdefi/cloc-action@main
      with:
        options: "--exclude-lang=YAML --json --report-file=cloc-report.json"
    - name: Collect codegen report
      if: ${{ always() }}
      run: |
        cat codebuild.out | jq --raw-input . | jq --slurp '{"messages" : .}' > codebuild-messages.json
        jq '{"cloc" : .}' cloc-report.json > cloc-report-sub.json
        jq -s 'add' codebuild-messages.json cloc-report-sub.json \
          | jq --arg timestamp "$(date)" --arg exitcode ${{ steps.codebuild.outputs.status }} '. += $ARGS.named' \
          > codebuild-report.json
    - name: Archive codebuild report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: codebuild-report
        path: codebuild-report.json
        retention-days: 30

  codetest:
    runs-on: ubuntu-latest
    needs: codebuild
    continue-on-error: false

    permissions:
      contents: read
      packages: read
      attestations: read

    outputs:
      status-code: ${{ steps.codetest.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Copy Codetest action
      uses: actions/checkout@v4
      with:
        repository: loonwerks/INSPECTA-Codetest-CI-Action
        path: INSPECTA-Codetest-CI-Action
    - name: Download built artifacts
      uses: actions/download-artifact@v4
      with:
        name: codebuild-built-artifacts
    - name: Code Test
      id : codetest
      uses: ./INSPECTA-Codetest-CI-Action
      with:
        sourcepath: software/hamr/microkit
    - name: Get codetest timestamp
      run: echo "Codetest timestamp is ${{ steps.codetest.outputs.timestamp }}"
    - name: Get codetest status
      run: echo "Codetest status is ${{ steps.build.codetest.outputs.status }}"
    - name: Echo status to output
      run: echo "status=${{ steps.codetest.outputs.status }}" >> "$GITHUB_OUTPUT"
    - name: Archive built artifacts
      uses: actions/upload-artifact@v4
      with:
        name: codetest-built-artifacts
        path: software/hamr/microkit
        retention-days: 30
    - name: Collect codetest report
      if: ${{ always() }}
      run: |
        cat codetest.out | jq --raw-input . | jq --slurp '{"messages" : .}' > codetest-messages.json
        cat codetest-messages.json \
          | jq --arg timestamp "$(date)" --arg exitcode ${{ steps.codetest.outputs.status }} '. += $ARGS.named' \
          > codetest-report.json
    - name: Archive codetest report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: codetest-report
        path: codetest-report.json
        retention-days: 30
  attestation:
    runs-on: ubuntu-latest
    continue-on-error: false

    permissions:
      contents: read
      packages: read
      attestations: read

    outputs:
      status-code: ${{ steps.resolute.outputs.status }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v4
    - name: Copy Resolute action
      uses: actions/checkout@v4
      with:
        repository: loonwerks/INSPECTA-Resolute-CI-Action
        path: INSPECTA-Resolute-CI-Action
    - name: Resolute Analysis
      id : resolute
      uses: ./INSPECTA-Resolute-CI-Action
      with:
        workspace_location: software/assurance
        output_path: software/assurance/resolute.json
        component_to_analyze: ardupilot_assurance::ArduPilot.i
        attestation_path: software/hamr/microkit/attestation
    - name: Get analysis timestamp
      run: echo "Resolute timestamp is ${{ steps.resolute.outputs.timestamp }}"
    - name: Get analysis status
      run: echo "Resolute status is ${{ steps.resolute.outputs.status }}"
    - name: Echo status to output
      run: echo "status=${{ steps.resolute.outputs.status }}" >> "$GITHUB_OUTPUT"
    - name: Archive resolute report
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: resolute-report
        path: software/assurance/resolute.json
        retention-days: 30

  reports:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [verify, codetest, attestation]
    continue-on-error: false

    permissions:
      artifact-metadata: read
      contents: write
      packages: read
      attestations: read
      pages: write
      id-token: write

    steps:
    - name: Download logika report artifact
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v3 # Use this community action
      with:
        workflow: analysis_and_codegen.yml # The filename of the workflow that uploaded the artifact
        workflow_conclusion: completed
        name: logika-analysis-report
        branch: feb-2026 # Specify the branch of the run, if needed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        path: public
    - name: Download logika feedback artifact
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v3 # Use this community action
      with:
        workflow: analysis_and_codegen.yml # The filename of the workflow that uploaded the artifact
        workflow_conclusion: completed
        name: logika-feedback
        branch: feb-2026 # Specify the branch of the run, if needed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        path: public
    - name: Download codegen report artifact
      continue-on-error: true
      uses: dawidd6/action-download-artifact@v3 # Use this community action
      with:
        workflow: analysis_and_codegen.yml # The filename of the workflow that uploaded the artifact
        workflow_conclusion: completed
        name: codegen-report
        branch: feb-2026 # Specify the branch of the run, if needed
        github_token: ${{ secrets.GITHUB_TOKEN }}
        path: public
    - name: Download verification report artifact
      continue-on-error: true
      uses: actions/download-artifact@v5
      with:
        name: verus-analysis-report
        path: public
    - name: Download codebuild report artifact
      continue-on-error: true
      uses: actions/download-artifact@v5
      with:
        name: codebuild-report
        path: public
    - name: Download codetest report artifact
      continue-on-error: true
      uses: actions/download-artifact@v5
      with:
        name: codetest-report
        path: public
     - name: Download resolute report artifact
      continue-on-error: true
      uses: actions/download-artifact@v5
      with:
        name: resolute-report
        path: public
    - name: Upload report to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: public
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4

  status-check:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [verify, codebuild, codetest, attestation, reports]
    continue-on-error: false

    steps:
    - name: check-exit-codetest
      env:
        VERIFY_STATUS: ${{ needs.verify.outputs.status-code }}
        CODEBUILD_STATUS: ${{ needs.codebuild.outputs.status-code }}
        CODETEST_STATUS: ${{ needs.codetest.outputs.status-code }}
        ATTESTATION_STATUS: ${{ needs.attestation.outputs.status-code }}
      run: |
        echo "needs.verify.outputs.status-code: $VERIFY_STATUS"
        echo "needs.codebuild.outputs.status-code: $CODEBUILD_STATUS"
        echo "needs.codetest.outputs.status-code: $CODETEST_STATUS"
        echo "needs.attestation.outputs.status-code: $ATTESTATION_STATUS"
        test $VERIFY_STATUS -eq 0 \
          && test $CODEBUILD_STATUS -eq 0 \
          && test $CODETEST_STATUS -eq 0 \
          && test $ATTESTATION_STATUS -eq 0